version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    container_name: clickise-backend
    restart: unless-stopped
    working_dir: /var/www
    depends_on:
      - db
    volumes:
      - ./backend:/var/www
    command: sh -c "php artisan migrate --force && php artisan db:seed && php-fpm"
    networks:
      - clickise-network

  db:
    image: mysql:8.0
    container_name: clickise-db
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - .docker/db/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - clickise-network

  web:
    image: nginx:alpine
    container_name: clickise-web
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/var/www
      - ./docker/backend/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - clickise-network

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - ./frontend/dist:/usr/share/nginx/html
    restart: unless-stopped

networks:
  clickise-network:
    driver: bridge

volumes:
  dbdata:
    driver: local